spring:
  security:
    oauth2:
       resourceserver:
         jwt:
           issuer-uri: http://localhost:8080/realms/liqui-vista
  datasource:
    url: jdbc:postgresql://localhost:5432/user-management-service
    username: postgres
    password: cdac
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

server:
  port: 9803

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9762/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
  queue:
    json:
      name: first_success_queue
  exchange:
    name: first_success_exchange
  routing:
    key: first_success_routing_key
  response:
    queue:
      name: response_queue
    exchange:
      name: response_exchange
    routing:
      key: response_routing_key
